# collectionbuilder-gh
# a Jekyll Digital Collection Generator
# designed for GitHub Pages

# Site settings


# creator contact email for meta tags
email: ewilliamson@uidaho.edu
# collection project date, when did you publish this
collection-date: "2019"

# url is your gh-pages base, following the pattern: username.github.io
url: https://collectionbuilder.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /collectionbuilder-gh


# google services [optional!]
# leave these blank or comment out to NOT include google code
google-tracking-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

# build settings
permalink: pretty

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
