# collectionbuilder-gh
# a Jekyll Digital Collection Generator
# designed for GitHub Pages

# Site settings

# title of site appears in banner
title: CollectionBuilder Demo
# tagline appears in banner
tagline: a theme for building simple digital exhibits
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "CollectionBuilder-GH is a template for creating small digital collection exhibits on GitHub Pages designed for teaching digital library skills"
# keywords appear in meta tags
keywords: "university of idaho, digital collections, digital humanities"
# creator of the digital collection, to appear in meta tags
author: evanwill
# creator contact email for meta tags
email: ewilliamson@uidaho.edu
# collection project date, when did you publish this
collection-date: "2018"

# url is your gh-pages base, following the pattern: username.github.io
url: https://collectionbuilder.github.io
# baseurl is your github repository's name prefixed with a /
baseurl: /collectionbuilder-gh
# repository is the github repository's full url
repository: https://github.com/CollectionBuilder/collectionbuilder-gh

# google services [optional!]
# leave these blank or comment out to NOT include google code
google-tracking-id: "UA-74844011-1"
# google-cse-id: "002151703305773322890:1pu3smhw1t8"

# build settings
permalink: pretty

# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
